services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api:8000
      - NEXT_PUBLIC_BASE_URL=https://api.notablenomads.com/v1/
      - NEXT_PUBLIC_GA_ID=GTM-KLT6DHJF
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
