/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/newDuck/scene.gltf 
Author: TadenStar (https://sketchfab.com/tadenstar)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cute-little-duck-7d731ce780534a01b5a11f72f7e93fd2
Title: Cute little Duck
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.5}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.DuckYellowBody} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.OrangSkin} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
