/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/long-duck.glb --t 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh;
    duck001_1: THREE.Mesh;
    duck001_2: THREE.Mesh;
    duck001_3: THREE.Mesh;
    duck001_4: THREE.Mesh;
    duck001_5: THREE.Mesh;
    duck001_6: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
    ["Material__133.001"]: THREE.MeshStandardMaterial;
    ["Material__146.001"]: THREE.MeshStandardMaterial;
    ["Material__134.001"]: THREE.MeshStandardMaterial;
    ["Material__75.001"]: THREE.MeshStandardMaterial;
    ["Material__28.001"]: THREE.MeshStandardMaterial;
    ["Material__27.001"]: THREE.MeshStandardMaterial;
  };
};

export function LongDuckModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/long-duck.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.duck001_1.geometry}
          material={materials["Material__133.001"]}
        />
        <mesh
          geometry={nodes.duck001_2.geometry}
          material={materials["Material__146.001"]}
        />
        <mesh
          geometry={nodes.duck001_3.geometry}
          material={materials["Material__134.001"]}
        />
        <mesh
          geometry={nodes.duck001_4.geometry}
          material={materials["Material__75.001"]}
        />
        <mesh
          geometry={nodes.duck001_5.geometry}
          material={materials["Material__28.001"]}
        />
        <mesh
          geometry={nodes.duck001_6.geometry}
          material={materials["Material__27.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/long-duck.glb");
