/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/voxelDuck/source/duck.glb --transform --types 
Files: ./public/voxelDuck/source/duck.glb [12.72KB] > /Users/miladghamati/Documents/web/nn-landing/duck-transformed.glb [3.88KB] (69%)
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    node_id3: THREE.Mesh;
  };
  materials: {
    ["51"]: THREE.MeshStandardMaterial;
  };
};

export function PixeledDuck(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/duck-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.node_id3.geometry}
        material={materials["51"]}
        position={[-0.118, -0.335, -0.059]}
        scale={0.394}
      />
    </group>
  );
}

useGLTF.preload("/models/duck-transformed.glb");
