/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/plastic_ducks_bag/scene.gltf --transform --types 
Files: ./public/plastic_ducks_bag/scene.gltf [23.02KB] > /Users/miladghamati/Documents/web/nn-landing/scene-transformed.glb [1.04MB] (-4428%)
Author: Simon Laisné (https://sketchfab.com/350rdlc.sl)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/plastic-ducks-bag-5849f98ac0a142749dec02a68548dec3
Title: Plastic Ducks Bag
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Line002_PlasticDuck_bag_0: THREE.Mesh;
  };
  materials: {
    PlasticDuck_bag: THREE.MeshStandardMaterial;
  };
};

export function PlasticDuckModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/plastic-duck-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Line002_PlasticDuck_bag_0.geometry}
        material={materials.PlasticDuck_bag}
        position={[0.004, 0.3, -0.004]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}
      />
    </group>
  );
}

useGLTF.preload("/models/plastic-duck-transformed.glb");
